### 1절. 파생변수 생성

#### 1. data.frame$

(생략)

#### 2. transform

``` r
head(iris)
```

    ##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
    ## 1          5.1         3.5          1.4         0.2  setosa
    ## 2          4.9         3.0          1.4         0.2  setosa
    ## 3          4.7         3.2          1.3         0.2  setosa
    ## 4          4.6         3.1          1.5         0.2  setosa
    ## 5          5.0         3.6          1.4         0.2  setosa
    ## 6          5.4         3.9          1.7         0.4  setosa

``` r
head(transform(iris, Sum.Length = Sepal.Length + Petal.Length))
```

    ##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species Sum.Length
    ## 1          5.1         3.5          1.4         0.2  setosa        6.5
    ## 2          4.9         3.0          1.4         0.2  setosa        6.3
    ## 3          4.7         3.2          1.3         0.2  setosa        6.0
    ## 4          4.6         3.1          1.5         0.2  setosa        6.1
    ## 5          5.0         3.6          1.4         0.2  setosa        6.4
    ## 6          5.4         3.9          1.7         0.4  setosa        7.1

#### 3. within

``` r
head(iris)
```

    ##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
    ## 1          5.1         3.5          1.4         0.2  setosa
    ## 2          4.9         3.0          1.4         0.2  setosa
    ## 3          4.7         3.2          1.3         0.2  setosa
    ## 4          4.6         3.1          1.5         0.2  setosa
    ## 5          5.0         3.6          1.4         0.2  setosa
    ## 6          5.4         3.9          1.7         0.4  setosa

``` r
table(iris$Species)
```

    ## 
    ##     setosa versicolor  virginica 
    ##         50         50         50

``` r
head(within(iris, {
  category = numeric(0) # 새로운 변수 생성 시 필요
  category[Species == 'setosa'] <- 1
  category[Species == 'versicolor'] <- 2
  category[Species == 'virginica'] <- 3
  category = factor(category)
}))
```

    ##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species category
    ## 1          5.1         3.5          1.4         0.2  setosa        1
    ## 2          4.9         3.0          1.4         0.2  setosa        1
    ## 3          4.7         3.2          1.3         0.2  setosa        1
    ## 4          4.6         3.1          1.5         0.2  setosa        1
    ## 5          5.0         3.6          1.4         0.2  setosa        1
    ## 6          5.4         3.9          1.7         0.4  setosa        1

### 2절. 변수 축소

#### 1. 주성분 분석 - prcomp, princomp

-   상관관계

``` r
head(USArrests)
```

    ##            Murder Assault UrbanPop Rape
    ## Alabama      13.2     236       58 21.2
    ## Alaska       10.0     263       48 44.5
    ## Arizona       8.1     294       80 31.0
    ## Arkansas      8.8     190       50 19.5
    ## California    9.0     276       91 40.6
    ## Colorado      7.9     204       78 38.7

``` r
pairs(USArrests, panel = panel.smooth, main = 'USArrests data')
```

![](2장.-데이터-변환_files/figure-markdown_github/pairs-1.png)

=\> Murder와 UrbanPop간의 연관성 작음.

-   주성분 분석 - 주성분 개수 결정

1.  기여율

``` r
US.prin <- princomp(USArrests, cor=TRUE)
summary(US.prin)
```

    ## Importance of components:
    ##                           Comp.1    Comp.2    Comp.3     Comp.4
    ## Standard deviation     1.5748783 0.9948694 0.5971291 0.41644938
    ## Proportion of Variance 0.6200604 0.2474413 0.0891408 0.04335752
    ## Cumulative Proportion  0.6200604 0.8675017 0.9566425 1.00000000

=\> 재2주성분에서의 누적기여율(Cumulative Proportion)이 85% 이상이므로
2번째 주성분까지 선택하는 것이 적절하다.

1.  스크리 산점도(scree plot)

``` r
plot(US.prin, type ='l')
```

![](2장.-데이터-변환_files/figure-markdown_github/scree_plot-1.png)

=\> 3번째 주성분에서 기울기가 급격하게 줄어듦으로 제2주성분까지 선택하는
것이 적절하다.

-   주성분계수 : 변수가 주성분에 기여하는 가중치

``` r
US.prin$loadings
```

    ## 
    ## Loadings:
    ##          Comp.1 Comp.2 Comp.3 Comp.4
    ## Murder    0.536  0.418  0.341  0.649
    ## Assault   0.583  0.188  0.268 -0.743
    ## UrbanPop  0.278 -0.873  0.378  0.134
    ## Rape      0.543 -0.167 -0.818       
    ## 
    ##                Comp.1 Comp.2 Comp.3 Comp.4
    ## SS loadings      1.00   1.00   1.00   1.00
    ## Proportion Var   0.25   0.25   0.25   0.25
    ## Cumulative Var   0.25   0.50   0.75   1.00

제1주성분분석 : 0.536\*Murder + 0.583\*Assault + 0.278\*UrbanPop +
0.543\*Rape

제2주성분분석 : 0.418\*Murder + 0.188\*Assault - 0.873\*UrbanPop -
0.167\*Rape

-   scores(주성분점수) : 주성분들의 선형식을 통해 계산된 각 행별 좌표

``` r
US.prin$scores
```

    ##                     Comp.1      Comp.2      Comp.3       Comp.4
    ## Alabama         0.98556588  1.13339238  0.44426879  0.156267145
    ## Alaska          1.95013775  1.07321326 -2.04000333 -0.438583440
    ## Arizona         1.76316354 -0.74595678 -0.05478082 -0.834652924
    ## Arkansas       -0.14142029  1.11979678 -0.11457369 -0.182810896
    ## California      2.52398013 -1.54293399 -0.59855680 -0.341996478
    ## Colorado        1.51456286 -0.98755509 -1.09500699  0.001464887
    ## Connecticut    -1.35864746 -1.08892789  0.64325757 -0.118469414
    ## Delaware        0.04770931 -0.32535892  0.71863294 -0.881977637
    ## Florida         3.01304227  0.03922851  0.57682949 -0.096284752
    ## Georgia         1.63928304  1.27894240  0.34246008  1.076796812
    ## Hawaii         -0.91265715 -1.57046001 -0.05078189  0.902806864
    ## Idaho          -1.63979985  0.21097292 -0.25980134 -0.499104101
    ## Illinois        1.37891072 -0.68184119  0.67749564 -0.122021292
    ## Indiana        -0.50546136 -0.15156254 -0.22805484  0.424665700
    ## Iowa           -2.25364607 -0.10405407 -0.16456432  0.017555916
    ## Kansas         -0.79688112 -0.27016470 -0.02555331  0.206496428
    ## Kentucky       -0.75085907  0.95844029  0.02836942  0.670556671
    ## Louisiana       1.56481798  0.87105466  0.78348036  0.454728038
    ## Maine          -2.39682949  0.37639158  0.06568239 -0.330459817
    ## Maryland        1.76336939  0.42765519  0.15725013 -0.559069521
    ## Massachusetts  -0.48616629 -1.47449650  0.60949748 -0.179598963
    ## Michigan        2.10844115 -0.15539682 -0.38486858  0.102372019
    ## Minnesota      -1.69268181 -0.63226125 -0.15307043  0.067316885
    ## Mississippi     0.99649446  2.39379599  0.74080840  0.215508013
    ## Missouri        0.69678733 -0.26335479 -0.37744383  0.225824461
    ## Montana        -1.18545191  0.53687437 -0.24688932  0.123742227
    ## Nebraska       -1.26563654 -0.19395373 -0.17557391  0.015892888
    ## Nevada          2.87439454 -0.77560020 -1.16338049  0.314515476
    ## New Hampshire  -2.38391541 -0.01808229 -0.03685539 -0.033137338
    ## New Jersey      0.18156611 -1.44950571  0.76445355  0.243382700
    ## New Mexico      1.98002375  0.14284878 -0.18369218 -0.339533597
    ## New York        1.68257738 -0.82318414  0.64307509 -0.013484369
    ## North Carolina  1.12337861  2.22800338  0.86357179 -0.954381667
    ## North Dakota   -2.99222562  0.59911882 -0.30127728 -0.253987327
    ## Ohio           -0.22596542 -0.74223824  0.03113912  0.473915911
    ## Oklahoma       -0.31178286 -0.28785421  0.01530979  0.010332321
    ## Oregon          0.05912208 -0.54141145 -0.93983298 -0.237780688
    ## Pennsylvania   -0.88841582 -0.57110035  0.40062871  0.359061124
    ## Rhode Island   -0.86377206 -1.49197842  1.36994570 -0.613569430
    ## South Carolina  1.32072380  1.93340466  0.30053779 -0.131466685
    ## South Dakota   -1.98777484  0.82334324 -0.38929333 -0.109571764
    ## Tennessee       0.99974168  0.86025130 -0.18808295  0.652864291
    ## Texas           1.35513821 -0.41248082  0.49206886  0.643195491
    ## Utah           -0.55056526 -1.47150461 -0.29372804 -0.082314047
    ## Vermont        -2.80141174  1.40228806 -0.84126309 -0.144889914
    ## Virginia       -0.09633491  0.19973529 -0.01171254  0.211370813
    ## Washington     -0.21690338 -0.97012418 -0.62487094 -0.220847793
    ## West Virginia  -2.10858541  1.42484670 -0.10477467  0.131908831
    ## Wisconsin      -2.07971417 -0.61126862  0.13886500  0.184103743
    ## Wyoming        -0.62942666  0.32101297  0.24065923 -0.166651801

ex) Alabama의 각 행별 좌표 : (0.98556588, 1.13339238, 0.44426879,
0.156267145)

-   행렬도 : 제1주성분과 제2주성분으로 이루어진 좌표평면상에
    주성분점수를 나타낸 산점도

``` r
biplot(US.prin,scale = 0)
```

![](2장.-데이터-변환_files/figure-markdown_github/biplot-1.png)

#### 2. 요인분석

``` r
data("swiss")
str(swiss)
```

    ## 'data.frame':    47 obs. of  6 variables:
    ##  $ Fertility       : num  80.2 83.1 92.5 85.8 76.9 76.1 83.8 92.4 82.4 82.9 ...
    ##  $ Agriculture     : num  17 45.1 39.7 36.5 43.5 35.3 70.2 67.8 53.3 45.2 ...
    ##  $ Examination     : int  15 6 5 12 17 9 16 14 12 16 ...
    ##  $ Education       : int  12 9 5 7 15 7 7 8 7 13 ...
    ##  $ Catholic        : num  9.96 84.84 93.4 33.77 5.16 ...
    ##  $ Infant.Mortality: num  22.2 22.2 20.2 20.3 20.6 26.6 23.6 24.9 21 24.4 ...

``` r
head(swiss)
```

    ##              Fertility Agriculture Examination Education Catholic
    ## Courtelary        80.2        17.0          15        12     9.96
    ## Delemont          83.1        45.1           6         9    84.84
    ## Franches-Mnt      92.5        39.7           5         5    93.40
    ## Moutier           85.8        36.5          12         7    33.77
    ## Neuveville        76.9        43.5          17        15     5.16
    ## Porrentruy        76.1        35.3           9         7    90.57
    ##              Infant.Mortality
    ## Courtelary               22.2
    ## Delemont                 22.2
    ## Franches-Mnt             20.2
    ## Moutier                  20.3
    ## Neuveville               20.6
    ## Porrentruy               26.6

-   min-max 정규화(뒤에 설명)

``` r
Min <- apply(swiss,2,min)
Max <- apply(swiss,2,max)
swiss_fa <- scale(swiss, center=Min, scale = (Max-Min))
head(swiss_fa)
```

    ##              Fertility Agriculture Examination  Education   Catholic
    ## Courtelary   0.7860870   0.1785311  0.35294118 0.21153846 0.07981604
    ## Delemont     0.8365217   0.4960452  0.08823529 0.15384615 0.84506898
    ## Franches-Mnt 1.0000000   0.4350282  0.05882353 0.07692308 0.93254982
    ## Moutier      0.8834783   0.3988701  0.26470588 0.11538462 0.32314768
    ## Neuveville   0.7286957   0.4779661  0.41176471 0.26923077 0.03076137
    ## Porrentruy   0.7147826   0.3853107  0.17647059 0.11538462 0.90362800
    ##              Infant.Mortality
    ## Courtelary          0.7215190
    ## Delemont            0.7215190
    ## Franches-Mnt        0.5949367
    ## Moutier             0.6012658
    ## Neuveville          0.6202532
    ## Porrentruy          1.0000000

-   요인의 개수

1.  고유값

``` r
swiss.prin <- princomp(swiss, cor = TRUE)
summary(swiss.prin)
```

    ## Importance of components:
    ##                           Comp.1    Comp.2    Comp.3     Comp.4     Comp.5
    ## Standard deviation     1.7887865 1.0900955 0.9206573 0.66251693 0.45225403
    ## Proportion of Variance 0.5332928 0.1980514 0.1412683 0.07315478 0.03408895
    ## Cumulative Proportion  0.5332928 0.7313442 0.8726125 0.94576729 0.97985624
    ##                            Comp.6
    ## Standard deviation     0.34765292
    ## Proportion of Variance 0.02014376
    ## Cumulative Proportion  1.00000000

``` r
swiss.prin$sdev^2
```

    ##    Comp.1    Comp.2    Comp.3    Comp.4    Comp.5    Comp.6 
    ## 3.1997570 1.1883082 0.8476098 0.4389287 0.2045337 0.1208626

``` r
swiss.prin$sdev
```

    ##    Comp.1    Comp.2    Comp.3    Comp.4    Comp.5    Comp.6 
    ## 1.7887865 1.0900955 0.9206573 0.6625169 0.4522540 0.3476529

고유값(standard deviation의 제곱)이 1 이상인 요인들로 결정 =\> 요인의
수를 2개로 결정

1.  scree plot

``` r
plot(swiss.prin, type = 'l')
```

![](2장.-데이터-변환_files/figure-markdown_github/n_factors2-1.png)

=\> 제2주성분에서 기울기가 완만해지므로 요인의 수를 1개로 결정

-   요인분석

``` r
factanal(swiss_fa, factors=2) # rotation = 'varimax'
```

    ## 
    ## Call:
    ## factanal(x = swiss_fa, factors = 2)
    ## 
    ## Uniquenesses:
    ##        Fertility      Agriculture      Examination        Education 
    ##            0.420            0.492            0.270            0.005 
    ##         Catholic Infant.Mortality 
    ##            0.061            0.960 
    ## 
    ## Loadings:
    ##                  Factor1 Factor2
    ## Fertility        -0.652   0.393 
    ## Agriculture      -0.631   0.333 
    ## Examination       0.685  -0.510 
    ## Education         0.997         
    ## Catholic         -0.124   0.961 
    ## Infant.Mortality          0.175 
    ## 
    ##                Factor1 Factor2
    ## SS loadings      2.311   1.481
    ## Proportion Var   0.385   0.247
    ## Cumulative Var   0.385   0.632
    ## 
    ## Test of the hypothesis that 2 factors are sufficient.
    ## The chi square statistic is 20.99 on 4 degrees of freedom.
    ## The p-value is 0.000318

Cumulative Var : 요인별 해당 값의 누적치 =\> 2개의 요인은 전체 데이터
분산의 약 63%를 설명

### 3절. 표준화와 정규화

#### 1.표준화

-   scale(data, center = TRUE, scale = TRUE)
    -   center : 데이터에서 벡터의 평균을 뱀
    -   scale : 표준편차 or RMS으로 나눔

``` r
data("mtcars")
str(mtcars)
```

    ## 'data.frame':    32 obs. of  11 variables:
    ##  $ mpg : num  21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...
    ##  $ cyl : num  6 6 4 6 8 6 8 4 4 6 ...
    ##  $ disp: num  160 160 108 258 360 ...
    ##  $ hp  : num  110 110 93 110 175 105 245 62 95 123 ...
    ##  $ drat: num  3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 ...
    ##  $ wt  : num  2.62 2.88 2.32 3.21 3.44 ...
    ##  $ qsec: num  16.5 17 18.6 19.4 17 ...
    ##  $ vs  : num  0 0 1 1 0 1 0 1 1 1 ...
    ##  $ am  : num  1 1 1 0 0 0 0 0 0 0 ...
    ##  $ gear: num  4 4 4 3 3 3 3 4 4 4 ...
    ##  $ carb: num  4 4 1 1 2 1 4 2 2 4 ...

``` r
# 두 변수 추출
test.cars <- mtcars[,c('mpg','hp')]
head(test.cars)
```

    ##                    mpg  hp
    ## Mazda RX4         21.0 110
    ## Mazda RX4 Wag     21.0 110
    ## Datsun 710        22.8  93
    ## Hornet 4 Drive    21.4 110
    ## Hornet Sportabout 18.7 175
    ## Valiant           18.1 105

``` r
# 표준화한 변수 추가
test.cars <- transform(test.cars,
                       mpg_scale = scale(test.cars$mpg),
                       hp_scale = scale(test.cars$hp))
head(test.cars)
```

    ##                    mpg  hp  mpg_scale   hp_scale
    ## Mazda RX4         21.0 110  0.1508848 -0.5350928
    ## Mazda RX4 Wag     21.0 110  0.1508848 -0.5350928
    ## Datsun 710        22.8  93  0.4495434 -0.7830405
    ## Hornet 4 Drive    21.4 110  0.2172534 -0.5350928
    ## Hornet Sportabout 18.7 175 -0.2307345  0.4129422
    ## Valiant           18.1 105 -0.3302874 -0.6080186

#### 2. 정규화

-   min-max 정규화

1.  scale 함수

``` r
Min <- min(iris$Sepal.Length)
Max <- max(iris$Sepal.Length)

iris$SL_new <- scale(iris$Sepal.Length, center = Min, scale = Max-Min)

head(iris)
```

    ##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species     SL_new
    ## 1          5.1         3.5          1.4         0.2  setosa 0.22222222
    ## 2          4.9         3.0          1.4         0.2  setosa 0.16666667
    ## 3          4.7         3.2          1.3         0.2  setosa 0.11111111
    ## 4          4.6         3.1          1.5         0.2  setosa 0.08333333
    ## 5          5.0         3.6          1.4         0.2  setosa 0.19444444
    ## 6          5.4         3.9          1.7         0.4  setosa 0.30555556

1.  사용자 정의 함수

``` r
normalize <- function(x){
  return((x-min(x))/(max(x)-min(x)))
}


num <- c(50:500)

num_new <- normalize(num)
head(num_new)
```

    ## [1] 0.000000000 0.002222222 0.004444444 0.006666667 0.008888889 0.011111111
